### PR TITLE
refer lib instead of duplicate code

### PR DESCRIPTION
**Pull request by xilin**

### CODE REVIEW

**Comment by wangmchn** [comment]
Is it just use pod instead of duplicate code?
Haven't do it before. Can you just explain it?
=0=

**Comment by xilin** [comment]
Yes, it is just use the local code as pod location instead of duplicate code. See the `:path` in podfile.

**Comment by codwam** [comment]
这确实是个问题，我在Demo里面改了代码，然后外面的那个WMPageController没有改，我又得改一次那两个warning。。其实可以直接用文件夹引用到外面的文件夹，或者用pods引用到外面的文件夹。

**Comment by wangmchn** [comment]
Hey, @xilin , @codwam 
Would it be difficult for to debug when using pods?
When I use pods,need I always call `pod update` first in order to see whether the code works or not?
Tell me...I'm pool in this...
And thx a lot.

**Comment by xilin** [comment]
I believe it is not needed. You should only need to run `pod update` at the
first time to generate the project reference.

2015-11-25 23:32 GMT+08:00 Wang Ming <notifications@github.com>:

**Comment by wangmchn** [comment]
I have deleted some files in demo, and refer `WMPageController` to the demo project, Maybe it's easier for me.....
Thanks a lot.

**Comment by xilin** [comment]
That should also be a solution.

**Comment by wangmchn** [comment]
Thanks again!

**Comment by xilin** [comment]
You're welcome.
Thanks for the great lib.

2015-11-27 18:45 GMT+08:00 Wang Ming <notifications@github.com>:

**Pull request closed without merging**
